# Generated by Django 3.1.2 on 2020-12-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelUsuario',
            fields=[
                ('idnivelusuario', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('datanascimento', models.DateField()),
                ('password', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=100)),
                ('idnivelusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgtask.nivelusuario')),
            ],
        ),
    ]
