# Generated by Django 3.1.2 on 2020-12-10 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgtask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadeChamado',
            fields=[
                ('idprioridadechamado', models.AutoField(primary_key=True, serialize=False)),
                ('descprioridade', models.CharField(max_length=20)),
                ('tempo', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaCidadeSuporte',
            fields=[
                ('idsistemacidadesuporte', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=50)),
                ('servidor', models.CharField(max_length=50)),
                ('ipservidor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoChamado',
            fields=[
                ('idsituacaochamado', models.AutoField(primary_key=True, serialize=False)),
                ('descsituacao', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemChamado',
            fields=[
                ('idmensagemchamado', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('idusuariocriou', models.IntegerField()),
                ('dataregistro', models.DateField(auto_now=True)),
                ('lido', models.BooleanField(default=False)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgtask.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('idchamado', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('idmensagemchamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgtask.mensagemchamado')),
                ('idprioridadechamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgtask.prioridadechamado')),
                ('idsistemacidadesuporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgtask.sistemacidadesuporte')),
                ('idsituacaochamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgtask.situacaochamado')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgtask.usuario')),
            ],
        ),
    ]
