# Generated by Django 3.1.2 on 2020-12-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgtask', '0002_chamado_mensagemchamado_prioridadechamado_sistemacidadesuporte_situacaochamado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1),
        ),
    ]
